import { Constants } from "@common";
import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");
export default StyleSheet.create({
  container: {},
  img: {
    height: 75,
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: 10,
  },
  imgPower: {
    height: 100,
    resizeMode: "contain",
    alignSelf: "center",
    marginTop: 5,
  },
  imgFinger: {
    width: 60,
    height: 60,
    marginTop: 8,
    borderRadius: 50,
    opacity: 10000,
    marginLeft: 8,
  },
  imgLogo: {
    width: "100%",
    backgroundColor: "white",
    height: 100,
    marginTop: 87,
  },
  txt: {
    marginTop: 20,
    alignSelf: "center",
    fontSize: 17,
    color: "#EFEFF4",
    fontFamily: "DINNextLTArabic-Regular",
  },
  finger: {
    alignSelf: "center",
    marginTop: 6,
    backgroundColor: "white",
    width: 75,
    height: 75,
    borderRadius: 50,
    opacity: 100,
  },
  c1: {
    height: 130,
    width: 130,
    borderRadius: 1000,
    borderWidth: 1,
    alignSelf: "center",
    borderColor: "#6ac2e2",
    //opacity: 0.2,
    marginTop: "15%",
  },
  c2: {
    height: 110,
    width: 110,
    borderRadius: 110,
    borderWidth: 1.5,
    alignSelf: "center",
    borderColor: "white",
    opacity: 0.8,
    justifyContent: "center",
    marginTop: "7%",
  },
  c3: {
    height: 90,
    width: 90,
    borderRadius: 100,
    borderWidth: 2,
    alignSelf: "center",
    borderColor: "white",
    //justifyContent: "center",
    // marginTop: "10%",
  },
  txt1: {
    color: "white",
    marginTop: 25,
    fontSize: width < 700 ? 17 : 30,
    alignSelf: "center",
    fontFamily: "DINNextLTArabic-Regular",
  },
  txtPower: {
    color: "#EFEFF4",
    marginTop: 60,
    fontSize: 12,
    alignSelf: "center",
    fontFamily: "DINNextLTArabic-Regular",
  },
  txt2: {
    color: "white",
    marginTop: 60,
    fontSize: width < 700 ? 12 : 22,
    alignSelf: "center",
    fontFamily: "DINNextLTArabic-Regular",
  },
  txt3: {
    color: "white",
    // marginTop: "3%",
    fontSize: 15,
    alignSelf: "center",
    textDecorationLine: "underline",
    padding: 10,
    fontFamily: "DINNextLTArabic-Regular",
  },
});
