const Images = {
  // Logo: require("@images/icons/Logo.png"),
  jp: require("@images/icons/jp.png"),
  logoHeader: require("@images/icons/logoHeader.png"),
  loading: require("@images/icons/loading.gif"),
  logoHeaderWezara: require("@images/icons/logo-rtl.png"),
  finger: require("@images/icons/finger.png"),
  logoAr: require("@images/icons/logoAr.png"),
  Res: require("@images/icons/Res.png"),
  people: require("@images/icons/people.png"),
  OtpImg: require("@images/icons/OtpImg.png"),
  pen1: require("@images/icons/pen1.jpg"),
  pen2: require("@images/icons/pen2.jpg"),
  penTawqi3i1: require("@images/icons/pen.png"),
  penTawqi3i: require("@images/icons/pencil.png"),
  pdf: require("@images/icons/pdfImg.png"),
  BigBen: require("@images/svg/BigBen.png"),
  LogOut: require("@images/icons/LogOut.png"),
  Profile: require("@images/icons/Profile.png"),
  search: require("@images/icons/search.png"),
  english: require("@images/icons/english.png"),
  arabic: require("@images/icons/arabic.png"),
  pdfIcon: require("@images/icons/pdf-icon.png"),
};

export default Images;
